export function render() {
    return `
    <div id='home' data-server-rendered="true" style="dpadding: 0 20px">
        <h3>Home Page: I am global class.</h3>
        <span>我是home组件，尝试了服务器渲染和浏览器渲染, 是同步加载的。可以通过浏览器dev tools查看。</span>
        <h4>History Router:&nbsp;&nbsp;<a href="/list">list link</a>&nbsp;&nbsp;<a href="/detail">detail link</a></h4>
        <h4>V-model, input something.</h4>
        <input type="text" value="Hello">
        <p>Hello</p>
        <textarea cols="20">World !</textarea>
        <p>World !</p>  
        <h4>Computed attribute</h4>
        <p>Hello World !</p>
        <h4>V-on:click  <button>Change data</button></h4>
        <h4>V-html</h4>
        <div><p>I am generated by<strong style="color: red">&nbsp;v-html</strong></p></div>
        <h4>V-for <button>Change data</button</h4>
        <ul style="padding:15px">
            <li>曹操 对酒当歌，人生几何？</li>
            <li>李清照  知否？知否？应是绿肥红瘦。</li>
        </ul>
    </div>`;
}
