import MVVM from 'MVVM';
import styles from './homecss';

export const id = 'home';
export const template = `
    <div id=${id} style="display: none; padding: 0 20px">
        <h4>V-for <button v-on:click="changePeople">Change data</button></h4>
        <ul v-for="item in items">
            <li>{{ item.name }} {{ item.message }}</li>
        </ul>
    </div>
`;
export default new MVVM({
    // 多个空白符和换行符号会被html解析器处理成一个空白，要用多个&nbsp;或者<br>
    template,
    id,
    el: '#app',
    data() {
        return {
            // someStr: 'Hello',
            // className: styles.yellow,
            // child: {
            //     someStr: 'World !',
            //     htmlStr:
            //         '<p>I am generated by<strong style="color: red">&nbsp;v-html</strong></p>',
            // },
            items: [
                { name: '曹操', message: '对酒当歌，人生几何？' },
                // { name: '李清照', message: '知否？知否？应是绿肥红瘦。' },
            ],
        };
    },
    computed: {
        getHelloWord() {
            return `${this.someStr}  ${this.child.someStr}`;
        },
    },
    methods: {
        clickBtn() {
            const randomStrArr = ['郭嘉', '典韦', '夏侯惇'];
            this.someStr = randomStrArr[parseInt(Math.random() * 3, 10)];
            this.child.someStr = randomStrArr[parseInt(Math.random() * 3, 10)];
        },
        changePeople() {
            this.items = [
                { name: '李白', message: '呼儿将出换美酒，与尔同销万古愁。' },
                { name: '杜甫', message: '安得广厦千万间，大庇天下寒士俱欢颜。' },
            ];
        },
    },
});
